// Export utilities for code reviews

export interface ExportData {
  code: string
  language: string
  mode: string
  model: string
  timestamp: string
  review: string
  issues: string[]
  suggestions: string[]
}

export function exportAsJSON(data: ExportData): void {
  const dataStr = JSON.stringify(data, null, 2)
  const dataBlob = new Blob([dataStr], { type: 'application/json' })
  downloadFile(dataBlob, `review-${Date.now()}.json`)
}

export function exportAsMarkdown(data: ExportData): void {
  const markdown = `# Code Review Report

**Date:** ${data.timestamp}
**Language:** ${data.language}
**Model:** ${data.model}
**Mode:** ${data.mode}

## Original Code

\`\`\`${data.language}
${data.code}
\`\`\`

## Review

${data.review}

## Issues Found (${data.issues.length})

${data.issues.map((issue, i) => `${i + 1}. ${issue}`).join('\n')}

## Suggestions (${data.suggestions.length})

${data.suggestions.map((suggestion, i) => `${i + 1}. ${suggestion}`).join('\n')}

---
*Generated by AI Code Reviewer*
`

  const blob = new Blob([markdown], { type: 'text/markdown' })
  downloadFile(blob, `review-${Date.now()}.md`)
}

export function exportAsCSV(data: ExportData): void {
  const rows = [
    ['Field', 'Value'],
    ['Date', data.timestamp],
    ['Language', data.language],
    ['Model', data.model],
    ['Mode', data.mode],
    ['Review', data.review],
    ['Issues Count', data.issues.length.toString()],
    ['Suggestions Count', data.suggestions.length.toString()],
  ]

  const csv = rows.map((row) => row.map((cell) => `"${cell.replace(/"/g, '""')}"`).join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv' })
  downloadFile(blob, `review-${Date.now()}.csv`)
}

function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
